name: Deploy to Dev Server

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setting up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies
        run: npm i --force

      - name: Building project
        run: CI=false npm run build

      - name: Deploy to Dev Ubuntu Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER}}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/deploy/user"

      - name: Deploy to UAT Ubuntu Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.UAT_SERVER_IP }}
          username: ${{ secrets.UAT_SERVER_USER}}
          key: ${{ secrets.UAT_SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/deploy/user/Alpha-admin-2024-frontend"

      - name: Checking Server Status
        run: |
          # echo "SERVER_PORT=3000" >> $GITHUB_ENV
          echo "SERVER_NAME=Alpha-admin-2024-frontend-dev" >> $GITHUB_ENV
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://${{ secrets.DEV_SERVER_IP }})
          echo "STATUS_CODE=$STATUS_CODE" >> $GITHUB_ENV

      - name: Evaluating Server Status
        run: |
          if [ "${{ env.STATUS_CODE }}" -eq 200 ]; then
            echo "DISCORD_MESSAGE=New build is live on Dev server ${{ env.SERVER_NAME }}: ${{ secrets.DEV_SERVER_IP }}" >> $GITHUB_ENV
          else
            echo "DISCORD_MESSAGE=Deployment to Dev server failed ${{ env.SERVER_NAME }}: ${{ secrets.DEV_SERVER_IP }}" >> $GITHUB_ENV
          fi

      - name: Sending Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DEV_DISCORD_WEBHOOK_URL }}
        with:
          args: ${{ env.DISCORD_MESSAGE }}

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DEV_DISCORD_WEBHOOK_URL}}
        with:
          args: "New build is live on UAT server (Alpha-admin-2024-frontend-UAT):- 18.175.252.237:3001"
