name: Deploy to Dev Server

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setting up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies
        run: npm i --force

      - name: Building project
        run: CI=false npm run build

      - name: Deploy to Ubuntu Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER}}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/deploy/user"

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DEV_DISCORD_WEBHOOK_URL}}
        uses: Ilshidur/action-discord@master
        with:
          args: "New build is live on Dev server(Alpha-admin-2024-frontend-dev):- 18.170.28.15"
